### ISSUE TITLE
Add alts to images

### ISSUE THREAD

**Issue by samrobbins85** [samrobbins85/notes-site#51]
All of the images in the markdown files don't have alts, and there's a lot to get through.

You can find all the files in the `notes` directory

Comment on the issue if you need any help

**Comment by icoderharshit** [comment]
I can do this task ! Assign me :)

**Comment by icoderharshit** [comment]
I am new to learning JS, thought it to be created using HTML CSS buddy.

**Comment by icoderharshit** [comment]
Ohh! I didn't realise this lately, assign me,  will be looking into it and do the part soon :)

**Comment by samrobbins85** [comment]
I'm making the decision to unassign you and not assign anyone as this issue could be seen as an umbrella issue due to the number of images that need alts. So instead comment here which section you'll be working on before you start working.

**Comment by siddharthdeo99** [comment]
You can assign this task to me i will do asap.

**Comment by shivambhatia5432** [comment]
Is this issue still open?

**Comment by samrobbins85** [comment]
There hasn't been a PR yet, but others may be making some progress, not sure

**Comment by catcarbonell** [comment]
I’d like to help out!

**Comment by samrobbins85** [comment]
Oops didn't mean to close this, the PR doesn't add alts to the images in the markdown, so still lots of work to do!

**Comment by samrobbins85** [comment]
> I’d like to help out!

Any help is very much appreciated
