### ISSUE TITLE
Hey @samrobbins i have done your adding alt text on images work

### ISSUE THREAD

**Issue by siddharthdeo99** [samrobbins85/notes-site#60]
Hey @samrobbins i have done your adding alt text on images work  that you have been merged.
So is my that work will be consider for hacktoberfest 2020 , as their policy have been change due to spamming.
If my work could not counted then can you please add hacktoberfest accepted label.
Any help would be appreciated.

**Comment by samrobbins85** [comment]
Yeah of course, I'll check over the rules to make sure I do everything I need to do tomorrow

**Comment by samrobbins85** [comment]
According to the rules here https://hacktoberfest.digitalocean.com/hacktoberfest-update there's no action required because that PR merged and I have the hacktoberfest label on this repo
