### ISSUE TITLE
3rd Year Modules

### ISSUE THREAD

**Issue by morristheaverage** [samrobbins85/notes-site#71]
I assume you don't do every module available this year so are you accepting PRs for other people's notes? And if so for which modules?

**Comment by samrobbins85** [comment]
Yeah absolutely! 
I do:
* Algorithmic Game Theory
* Computational Complexity
* Computational Modelling in the Humanities and Social Sciences
* Design of Algorithms and Data Structures
* Individual Project
* Parallel Scientific Computing
* Recommender Systems

So any other than that. And I'll write up a bit of documentation about the components you can use in the markdown if you want to

**Comment by samrobbins85** [comment]
I've also just pushed a small change that allows for adding an author to the page, so add this to the frontmatter

```yml
author:
    name: "John Doe"
    github: "john-doe"
```

and it'll display your name with a link to your GitHub

**Comment by samrobbins85** [comment]
I've added the pages https://github.com/samrobbins85/notes-site/wiki/Components and https://github.com/samrobbins85/notes-site/wiki/Frontmatter to the wiki which should help you understand the features you can use in the pages

**Comment by morristheaverage** [comment]
looks great I'll have a go with bioinformatics and deep learning and reinforcement learning
